all: libTimer.a

GCC_DIR = /opt/ti/msp430_gcc/bin
SUPPORT_FILE_DIRECTORY = /opt/ti/msp430_gcc/include

CPU     = msp430g2553
CFLAGS  = -I $(SUPPORT_FILE_DIRECTORY) -mmcu=${CPU}

#switch the compiler (for the internal make rules)
CC      = $(GCC_DIR)/msp430-elf-gcc
AS      = $(GCC_DIR)/msp430-elf-as
AR      = $(GCC_DIR)/msp430-elf-ar

libTimer.a: clocksTimer.o sr.o
	$(AR) crs $@ $^

install: libTimer.a
	mkdir -p ../h ../lib
	mv $^ ../lib
	cp *. ../h

clean:
	rm -f timerLib.a *.o
